### ISSUE TITLE
Prod Issue - Contact forms : not receiving email

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/girl-scout-coders#16]
**Web Forms**
Contact Is
Request Patches

**Issue**
User receive successful message after submit. However, we don't received any email, neither on media@ nor on info@

**Comment by yahya-mekkawi** [comment]
Check and tell me?
Should be working now =)

**Comment by Code4SocialGood** [comment]
Works perfect now! Thanks.
Issue resolved and closed.
