### ISSUE TITLE
Page - Locations : Blue Marks

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/girl-scout-coders#3]
Link: https://dev.girlscoutcoders.org/about/locations/

- **Change Request 1**
Change the color from blue to orange: #f37021

- **Change Request 2**
Label AS-IS: GSC ambassadors available to assist local Girl Scouts
Label TO-BE: Regional Ambassadors

- **Change Request 3**
Label AS-IS: Greater Boston Area
Label TO-BE: Massachusetts

**Comment by yahya-mekkawi** [comment]
Done =)
